# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Function to convert C++ matrices to R matrices, written in R
#' @description Converts a 2D vector int to a NumericMatrix
#' @param m A 2D vector int object from C++ STL
GetMatrix <- function(m) {
    .Call(`_tRiad_GetMatrix`, m)
}

#' @title Implementation of the EDG subroutine, written in C++
#' @description Returns which edge of I is adjacent to J
#' @param I index of triangles I
#' @param J index of triangle J
#' @param e List of adjacent triangles
Edge <- function(I, J, e) {
    .Call(`_tRiad_Edge`, I, J, e)
}

#' @title Cross Product of AB and AP
#' @description Calculates cross product of AP and AP to check if P is left or right of AB
#' @param Px X component of point P
#' @param Py Y component of point P
#' @param Ax X component of point A
#' @param Ay Y component of point A
#' @param Bx X component of point B
#' @param By Y component of point B
LeftRight <- function(Px, Py, Ax, Ay, Bx, By) {
    .Call(`_tRiad_LeftRight`, Px, Py, Ax, Ay, Bx, By)
}

#'@title Implementation of the SWAP subroutine
#'@description Checks to see if triangle P-V2-V1 and V3-V1-V2 need to swap common edge
#'@param x1 X coordinate of V1
#'@param y1 Y coordinate of V1
#'@param x2 X coordinate of V2
#'@param y2 Y coordinate of V2
#'@param x3 X coordinate of V3
#'@param y3 Y coordinate of V3
#'@param xp X coordinate of P
#'@param yp Y coordinate of P
Swap <- function(x1, y1, x2, y2, x3, y3, xp, yp) {
    .Call(`_tRiad_Swap`, x1, y1, x2, y2, x3, y3, xp, yp)
}

#'@title Check which triangles a point lies within
#'@description Returns the index of the triangle which contains the given point
#'@param i index of the point to be located
#'@param x X coordinates of points
#'@param y Y coordinates of points
#'@param v Vertices of triangles, columns are triangle number and rows are vertices 1,2,3
#'@param e Adjacency of triangles, columns are triangle number and rows are ids of adjacent triangles
TriLoc <- function(i, x, y, v, e) {
    .Call(`_tRiad_TriLoc`, i, x, y, v, e)
}

#'@title Implementation of the DELAUN subroutine
#'@description Returns a Delaunay Triangulation but with normalised points
#'@param norm_x Normalised X coordinates of points
#'@param norm_y Normalised Y coordinates of points
Delaun <- function(norm_x, norm_y) {
    .Call(`_tRiad_Delaun`, norm_x, norm_y)
}

#'@title Constructor for the triad class, written in C++
#'@description An object which stores the information of all vertices and triangles for the Delaunay Triangulation
#'@param x Object of NumericVector class, X coordinates
#'@param y Object of NumericVector class, y coordinates
#'@param v Object of NumericMatrix class, List of triangles
NewTriad <- function(x, y, v) {
    .Call(`_tRiad_NewTriad`, x, y, v)
}

#' @title Implementation of the DELTRI subroutine, written in C++
#' @description returns an object of triad class, which can be plotted
#' @param x_ vector of X coordinates, if y_ is NULL, x_ is a data frame
#' @param y_ vector of Y coordinates
#' @importFrom Rcpp evalCpp
#' @useDynLib tRiad, .registration=TRUE
#' @export
DelTri <- function(x_, y_ = NULL) {
    .Call(`_tRiad_DelTri`, x_, y_)
}

